[package]
name = "bevy_procedural_tree"
description = "Procedurally generated 3D trees for bevy"
authors = ["Affinator"]
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Affinator/bevy_procedural_tree"
exclude = ["assets/", "examples/", "images/", "Changelog.md"]

[features]
default = []
u32_indices = []
inspector = ["bevy-inspector-egui"]
perf_ui = []

[dependencies]
bevy = { version = "0.17", default-features = false, features =  [
    "bevy_color",
    "bevy_pbr",
    "bevy_mesh",
    "multi_threaded",
    "std",
    "bevy_log"
]}
bevy-inspector-egui = { version = "0.34", optional = true }
fastrand = "2.3"

[dev-dependencies]
bevy = { version = "0.17", default-features = false, features =  [
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_asset",
    "bevy_gizmos",
    "bevy_log",
    "bevy_pbr",
    "bevy_render",
    "bevy_window",
    "bevy_winit",
    "bevy_ui_render",
    "hdr",
    "png",
    "dds",
    "multi_threaded",
    "std",
    "sysinfo_plugin",
    "wayland",
    "default_font",
    "sysinfo_plugin",
    "bevy_dev_tools"
]}

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
debug = false
strip = true
debug-assertions = false # for possible performance regressions (i.e. in WGPU)
overflow-checks = false

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
debug = false
strip = true

[[example]]
name = "showroom"
required-features = ["inspector"]
